<h1><font color='blue'> 8E and 8F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC

In [2]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)

### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


In [3]:
# you can write your code here
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)
X_train, X_cv, y_train, y_cv = train_test_split( X_train, y_train, test_size=0.25, random_state=42)

In [4]:
# training the model
svc = SVC(gamma = 0.001, C = 100)
svc.fit(X_train, y_train)
intercept = svc.intercept_
support_vectors = svc.support_vectors_
dual_coef = svc.dual_coef_ # holds product y_i * alpha_i
svc.decision_function(X_cv)

array([ 0.87725032, -1.11743611, -3.55849268, -0.63350034, -1.18015501,
       -1.26230537, -3.31529473, -2.41371053, -2.40420402, -1.40470136,
        2.2970529 , -3.22576386, -1.9212918 ,  0.32584349, -1.12030475,
        0.91878376, -3.53196895, -0.90712539,  1.94040278, -1.66111556,
       -2.90490653, -0.91760307, -4.02454269, -1.79689298, -3.3666262 ,
       -0.22984139,  1.61909328,  1.08220855, -4.13625152, -1.98400331,
       -2.86904577, -3.49054858, -2.39188038, -3.66248   , -3.377558  ,
        2.065262  , -0.59957309, -0.13877145,  2.46436749, -0.66577146,
       -2.76798275, -3.21889623, -0.98989632, -0.84182526,  1.99761518,
        1.14523061, -2.714945  ,  1.77289537, -3.43020555, -0.94459902,
       -2.85298676, -1.26031757, -3.11899783,  0.58079023, -3.74060563,
       -0.98686991, -0.84703576, -3.90563475,  1.4043297 ,  3.49968358,
        1.60837807, -1.77280515,  1.53703469, -2.53903571, -2.3817726 ,
       -3.29728798,  1.82646   ,  2.2368902 , -2.95930696, -1.94

In [5]:
def decision_function(X_cv, dual_coef, support_vectors):
    dec = []
    for xq in X_cv:
        # compute Kernel for each pt:  𝐾(𝑥𝑖,𝑥𝑞)  =  𝑒𝑥𝑝(−𝛾||𝑥𝑖−𝑥𝑞||2)
        summ = 0 
        for i in range(len(support_vectors)):
            summ += dual_coef[0][i] * np.exp(-0.001 * pow(np.linalg.norm(support_vectors[i] - xq, 2), 2))
        dec.append(summ + intercept[0])
    return dec

In [6]:
f_cv = np.array(decision_function(X_cv, dual_coef, support_vectors))
f_cv

array([ 0.87725032, -1.11743611, -3.55849268, -0.63350034, -1.18015501,
       -1.26230537, -3.31529473, -2.41371053, -2.40420402, -1.40470136,
        2.2970529 , -3.22576386, -1.9212918 ,  0.32584349, -1.12030475,
        0.91878376, -3.53196895, -0.90712539,  1.94040278, -1.66111556,
       -2.90490653, -0.91760307, -4.02454269, -1.79689298, -3.3666262 ,
       -0.22984139,  1.61909328,  1.08220855, -4.13625152, -1.98400331,
       -2.86904577, -3.49054858, -2.39188038, -3.66248   , -3.377558  ,
        2.065262  , -0.59957309, -0.13877145,  2.46436749, -0.66577146,
       -2.76798275, -3.21889623, -0.98989632, -0.84182526,  1.99761518,
        1.14523061, -2.714945  ,  1.77289537, -3.43020555, -0.94459902,
       -2.85298676, -1.26031757, -3.11899783,  0.58079023, -3.74060563,
       -0.98686991, -0.84703576, -3.90563475,  1.4043297 ,  3.49968358,
        1.60837807, -1.77280515,  1.53703469, -2.53903571, -2.3817726 ,
       -3.29728798,  1.82646   ,  2.2368902 , -2.95930696, -1.94

In [7]:
f_cv - svc.decision_function(X_cv)

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

<h2><font color='Geen'> 8F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm


In [8]:
# Transforming + and - classes
n = list(filter(lambda x : x == 0, y_train))
p = list(filter(lambda x : x == 1, y_train))
N_pos = len(p); N_neg = len(n)
y_pos = (N_pos + 1) / (N_pos + 2)
y_neg = 1 / (N_neg + 2)
y_tr_cv = np.array([y_pos if x == 1 else y_neg for x in y_cv])  

In [9]:
def initialize_weights(dim):
    ''' In this function, we will initialize our weights and bias'''
    #initialize the weights to zeros array of (1,dim) dimensions
    #you use zeros_like function to initialize zero, check this link https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html
    #initialize bias to zero
    w = np.zeros_like(dim, dtype=float)
    b = 0
    return w,b

def sigmoid(z):
    ''' In this function, we will return sigmoid of z'''
    # compute sigmoid(z) and return
    sig = 1/(1 + np.exp(-z))
    return sig

def gradient_dw(x,y,w,b,alpha,N):
    '''In this function, we will compute the gardient w.r.to w '''
    dw = x * (y - sigmoid(np.dot(w, x) + b)) - (alpha/N * w)
    return dw

def gradient_db(x,y,w,b):
    '''In this function, we will compute gradient w.r.to b '''
    db = y - sigmoid(np.dot(w.T, x) + b)
    return db

def logloss(w,b, X, Y):
    loss = 0
    for i in range(len(X)):
        loss += (Y[i]*np.log10(sigmoid(np.dot(w, X[i])+ b))) + ((1 - Y[i])* np.log10(1 - sigmoid(np.dot(w, X[i])+ b)))   
    return -loss/len(X)


In [26]:
train_loss = []
def train(X,Y,epochs,alpha,eta0):
    ''' In this function, we will implement logistic regression'''
    w, b  = initialize_weights(X[0])
    for e in range(epochs):
        y_pred_arr = []
        for i in range(len(X)):
            x = X[i]; y = Y[i]
            dw = gradient_dw(x,y, w, b, alpha, len(X))
            db = gradient_db(x, y, w, b)
            w = w + (eta0*dw)
            b = b + (eta0*db)  
        train_loss.append(logloss(w, b, X, Y))
    return w,b

In [11]:
f_test = np.array(decision_function(X_test, dual_coef, support_vectors))

In [27]:
alpha=0.0001
eta0=0.0001
N=len(X_train)
epochs=14
w,b=train(f_cv, y_tr_cv, epochs, alpha, eta0)
print(w, b)

0.6967562066111093 -0.11394393316560336


In [39]:
test_predict_proba = []
for i in f_test:
    test_predict_proba.append(sigmoid(np.dot(w,i)+ b))
print(test_predict_proba)

[0.2521519785814721, 0.2643393204543964, 0.36228997601265445, 0.13411831566855312, 0.06816671932259417, 0.603232922677178, 0.7412883969536055, 0.21962117442439322, 0.061280953283390116, 0.5254152579524135, 0.8226552598213283, 0.0878514474883959, 0.3552626214515223, 0.38656699608244444, 0.323641147546926, 0.7418492242362434, 0.1009477538180608, 0.11342850502243915, 0.11873397941849935, 0.21942778641919525, 0.18015526712207552, 0.054831192439336436, 0.813328389483455, 0.7226682696458899, 0.13311061900167528, 0.10135550260733608, 0.05832664196503788, 0.2942151843705387, 0.3125729712925916, 0.6428055498933694, 0.13415886598671353, 0.07453230506922255, 0.05481565315891693, 0.0924814855706721, 0.7427334802526574, 0.4830229963123732, 0.4601362628898521, 0.17067771506315232, 0.5802953868906251, 0.691757255531743, 0.08541210850228124, 0.5051523284540855, 0.5235926908626477, 0.48308855638610215, 0.09968737624327179, 0.76020147450372, 0.11713815240092455, 0.07696123116377378, 0.6573288489020089, 

In [40]:
pred = [1 if x>= 0.5 else 0 for x in test_predict_proba]

In [45]:
diff = np.array(pred) - y_test

In [48]:
correct_cls = list(filter(lambda x: x == 0, diff))
print(len(correct_cls))

930


In [47]:
print(len(y_test))

1000


In [49]:
print('accuracy = ', len(correct_cls)/ len(y_test))

accuracy =  0.93
